
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fariz
 */
public class mainFrm extends javax.swing.JFrame {

    String hrgMakanan, hrgMinuman, hrgTotal;  
    int hrgMkn, hrgMnm, totalHrg, totalHrgMkn, totalHrgMnm;
    /**
     * Creates new form mainFrm
     */
    public mainFrm() {
        initComponents();
        selectData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tHargaMakanan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tHargaMinuman = new javax.swing.JTextField();
        Tanggal = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        tTotalHarga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bClear = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        tMinuman = new javax.swing.JComboBox<>();
        tMakanan = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        spinnerMnm = new javax.swing.JSpinner();
        spinnerMkn = new javax.swing.JSpinner();
        tNamaKsr = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        bPrint1 = new javax.swing.JButton();
        bRefresh = new javax.swing.JButton();
        bBantuan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entry");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ENTRY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 90, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel2.setText("Nama makanan");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(11, 12, 190, 20);

        jLabel3.setText("Rp");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 290, 30, 30);

        tHargaMakanan.setEditable(false);
        tHargaMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tHargaMakananActionPerformed(evt);
            }
        });
        jPanel1.add(tHargaMakanan);
        tHargaMakanan.setBounds(30, 80, 180, 30);

        jLabel4.setText("Nama minuman");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 110, 190, 20);

        jLabel5.setText("Tanggal Pembelian");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 210, 190, 20);

        tHargaMinuman.setEditable(false);
        tHargaMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tHargaMinumanActionPerformed(evt);
            }
        });
        jPanel1.add(tHargaMinuman);
        tHargaMinuman.setBounds(30, 180, 180, 30);
        jPanel1.add(Tanggal);
        Tanggal.setBounds(10, 230, 200, 30);

        jLabel6.setText("Harga minuman");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 160, 190, 20);

        tTotalHarga.setEditable(false);
        jPanel1.add(tTotalHarga);
        tTotalHarga.setBounds(30, 290, 180, 30);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Total Harga :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(100, 270, 110, 20);

        bClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bClear.setText("CLEAR");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });
        jPanel1.add(bClear);
        bClear.setBounds(140, 330, 73, 40);

        bSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bSave.setText("SAVE");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        jPanel1.add(bSave);
        bSave.setBounds(70, 330, 73, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 270, 200, 10);

        tMinuman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Local greentea", "Toraja coffee", "'Mak' special coffee", "'Starbud' special coffee" }));
        tMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMinumanActionPerformed(evt);
            }
        });
        jPanel1.add(tMinuman);
        tMinuman.setBounds(10, 130, 200, 30);

        tMakanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indonesian salad with peanut sauce", "Grilled chicken", "Grilled fish", "Meatball" }));
        tMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMakananActionPerformed(evt);
            }
        });
        jPanel1.add(tMakanan);
        tMakanan.setBounds(10, 30, 200, 30);

        jLabel10.setText("Harga makanan");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 60, 190, 20);

        jLabel11.setText("Rp");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 80, 30, 30);

        jLabel12.setText("Rp");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 180, 30, 30);

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(10, 330, 50, 40);
        jPanel1.add(spinnerMnm);
        spinnerMnm.setBounds(220, 130, 40, 30);
        jPanel1.add(spinnerMkn);
        spinnerMkn.setBounds(220, 30, 40, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 40, 270, 380);
        getContentPane().add(tNamaKsr);
        tNamaKsr.setBounds(450, 50, 170, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Nama kasir");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(450, 30, 130, 20);

        bDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bDelete.setText("DELETE");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(bDelete);
        bDelete.setBounds(300, 40, 73, 40);

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Tanggal", "Nama kasir", "Nama makanan", "Harga makanan", "Nama minuman", "Harga minuman", "Total harga", "Diskon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelData);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 90, 640, 310);

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel13.setText("Setiap pembelian diatas 200.000 diberikan diskon 10%");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(300, 400, 250, 20);

        bPrint1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bPrint1.setText("PRINT");
        bPrint1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrint1ActionPerformed(evt);
            }
        });
        getContentPane().add(bPrint1);
        bPrint1.setBounds(370, 40, 69, 40);

        bRefresh.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        bRefresh.setText("Refresh");
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(bRefresh);
        bRefresh.setBounds(860, 40, 80, 30);

        bBantuan.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        bBantuan.setText("Bantuan");
        bBantuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBantuanActionPerformed(evt);
            }
        });
        getContentPane().add(bBantuan);
        bBantuan.setBounds(860, 10, 80, 30);

        setSize(new java.awt.Dimension(968, 472));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMakananActionPerformed
        if(tMakanan.getSelectedItem().equals("Indonesian salad with peanut sauce")) {
            tHargaMakanan.setText("45000");
            hrgMkn = Integer.parseInt(tHargaMakanan.getText());
        }
        if(tMakanan.getSelectedItem().equals("Grilled chicken")) {
            tHargaMakanan.setText("180000");
            hrgMkn = Integer.parseInt(tHargaMakanan.getText());
        }
        if(tMakanan.getSelectedItem().equals("Grilled fish")) {
            tHargaMakanan.setText("170000");
            hrgMkn = Integer.parseInt(tHargaMakanan.getText());
        }
        if(tMakanan.getSelectedItem().equals("Meatball")) {
            tHargaMakanan.setText("30000");
            hrgMkn = Integer.parseInt(tHargaMakanan.getText());
        };
    }//GEN-LAST:event_tMakananActionPerformed

    private void tHargaMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tHargaMakananActionPerformed
   
    }//GEN-LAST:event_tHargaMakananActionPerformed

    private void tMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMinumanActionPerformed
    if(tMinuman.getSelectedItem().equals("Local greentea")) {
            tHargaMinuman.setText("10000");
            hrgMnm = Integer.parseInt(tHargaMinuman.getText());
        }
        if(tMinuman.getSelectedItem().equals("Toraja coffee")) {
            tHargaMinuman.setText("15000");
            hrgMnm = Integer.parseInt(tHargaMinuman.getText());
        }
        if(tMinuman.getSelectedItem().equals("'Mak' special coffee")) {
            tHargaMinuman.setText("22000");
            hrgMnm = Integer.parseInt(tHargaMinuman.getText());
        }
        if(tMinuman.getSelectedItem().equals("'Starbud' special coffee")) {
            tHargaMinuman.setText("25000");
            hrgMnm = Integer.parseInt(tHargaMinuman.getText());
        }        
    }//GEN-LAST:event_tMinumanActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        int jumlahmakanan = (Integer) spinnerMkn.getValue();
        int jumlahminuman = (Integer) spinnerMnm.getValue();
        
        totalHrgMkn = hrgMkn * jumlahmakanan;
        totalHrgMnm = hrgMnm * jumlahminuman;
        totalHrg = totalHrgMkn + totalHrgMnm;
        
        if(totalHrg > 200000)
        {
            totalHrg = totalHrg - totalHrg * 10/100;
            tTotalHarga.setText(Integer.toString(totalHrg));
        } else {
            tTotalHarga.setText(Integer.toString(totalHrg));
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tHargaMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tHargaMinumanActionPerformed
        
    }//GEN-LAST:event_tHargaMinumanActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        tHargaMakanan.setText("");
        tHargaMinuman.setText("");
        Tanggal.setDate(null);
        tTotalHarga.setText("");
        spinnerMkn.setValue(0);
        spinnerMnm.setValue(0);
    }//GEN-LAST:event_bClearActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(Tanggal.getDate());
        String namakasir = tNamaKsr.getText();
        String makanan = (String) tMakanan.getSelectedItem();
        int hargamakanan = Integer.parseInt(tHargaMakanan.getText());
        String minuman = (String) tMinuman.getSelectedItem();
        int hargaminuman = Integer.parseInt(tHargaMinuman.getText());
        int totalharga = Integer.parseInt(tTotalHarga.getText());
        
        String SQL = "INSERT INTO tb_pesan (tanggal,kasir,makanan,hargamakanan,minuman,hargaminuman,totalHarga)" +
                "VALUES('"+tanggal+"','"+namakasir+"','"+makanan+"',"+hargamakanan+",'"+
                minuman+"',"+hargaminuman+","+totalharga+")";
        int status = KoneksiDB.execute(SQL);
        if(status == 1) {
            JOptionPane.showMessageDialog(this, "Data berhasil ditambah", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
            selectData();
        } else {
            JOptionPane.showMessageDialog(this, "Data Gagal ditambah", "GAGAL", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bSaveActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        int baris = tabelData.getSelectedRow();
        if(baris != -1) {
            String id = tabelData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_pesan WHERE id='"+id+"'";
            int status = KoneksiDB.execute(SQL);
            if(status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris data dulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        selectData();
    }//GEN-LAST:event_bRefreshActionPerformed

    private void bPrint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrint1ActionPerformed
        MessageFormat header = new MessageFormat("Pesanan");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}");
        try {
            tabelData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch(java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_bPrint1ActionPerformed

    private void bBantuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBantuanActionPerformed
        JOptionPane.showMessageDialog(this, "Setelah memasukkan data, tekan tombol OK untuk menghitung lalu klik Save\n"
                + "Selalu klik Clear apabila akan memasukkan data baru", "Help", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bBantuanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Tanggal;
    private javax.swing.JButton bBantuan;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bPrint1;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bSave;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner spinnerMkn;
    private javax.swing.JSpinner spinnerMnm;
    private javax.swing.JTextField tHargaMakanan;
    private javax.swing.JTextField tHargaMinuman;
    private javax.swing.JComboBox<String> tMakanan;
    private javax.swing.JComboBox<String> tMinuman;
    private javax.swing.JTextField tNamaKsr;
    private javax.swing.JTextField tTotalHarga;
    private javax.swing.JTable tabelData;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"id", "Tanggal", "kasir", "makanan", "hargamakanan", "minuman", "hargaminuman", "totalHarga"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_pesan";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()) {
               String id = rs.getString(1);
               String Tanggal = rs.getString(2);
               String kasir = rs.getString(3);
               String makanan = rs.getString(4);
               String hargamakanan = rs.getString(5);
               String minuman = rs.getString(6);
               String hargaminuman = rs.getString(7);
               String totalHarga = rs.getString(8);
               
               String data[] = {id, Tanggal, kasir, makanan, hargamakanan, minuman, hargaminuman, totalHarga};
               dtm.addRow(data);
            }
        } catch(SQLException ex) {
            Logger.getLogger(mainFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabelData.setModel(dtm);
                
    }
}